package us.vombat.buildiblocks.init;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import us.vombat.buildiblocks.blocks.blocks.block.EmbellishedDiamondBlock;
import us.vombat.buildiblocks.blocks.blocks.block.EmbellishedEmeraldBlock;
import us.vombat.buildiblocks.blocks.blocks.block.EmbellishedGoldBlock;
import us.vombat.buildiblocks.blocks.blocks.block.EmbellishedIronBlock;
import us.vombat.buildiblocks.blocks.blocks.block.brick.AndesiteBrick;
import us.vombat.buildiblocks.blocks.blocks.block.brick.DioriteBrick;
import us.vombat.buildiblocks.blocks.blocks.block.brick.GraniteBrick;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.AcaciaCarved;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.BirchCarved;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.DarkoakCarved;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.JungleCarved;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.OakCarved;
import us.vombat.buildiblocks.blocks.blocks.block.carvedwood.SpruceCarved;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTile;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileBlack;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileBlue;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileBrown;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileCyan;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileGray;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileGreen;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileLightBlue;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileLime;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileMagenta;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileOrange;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTilePink;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTilePurple;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileRed;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileSilver;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileWhite;
import us.vombat.buildiblocks.blocks.blocks.block.claytile.ClayTileYellow;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakBlack;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakBlue;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakCyan;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakGray;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakGreen;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakLightBlue;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakLime;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakMagenta;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakOrange;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakPink;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakPurple;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakRed;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakSilver;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakWhite;
import us.vombat.buildiblocks.blocks.blocks.block.paintedplanks.PaintedOakYellow;
import us.vombat.buildiblocks.blocks.blocks.fence.DiamondFence;
import us.vombat.buildiblocks.blocks.blocks.fence.EmeraldFence;
import us.vombat.buildiblocks.blocks.blocks.fence.GoldFence;
import us.vombat.buildiblocks.blocks.blocks.fence.IronFence;
import us.vombat.buildiblocks.blocks.blocks.lattice.AcaciaLattice;
import us.vombat.buildiblocks.blocks.blocks.lattice.BirchLattice;
import us.vombat.buildiblocks.blocks.blocks.lattice.DarkOakLattice;
import us.vombat.buildiblocks.blocks.blocks.lattice.JungleLattice;
import us.vombat.buildiblocks.blocks.blocks.lattice.OakLattice;
import us.vombat.buildiblocks.blocks.blocks.lattice.SpruceLattice;
import us.vombat.buildiblocks.blocks.blocks.misc.PaperWall;
import us.vombat.buildiblocks.blocks.blocks.pathway.AcaciaPlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.BirchPlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.DarkOakPlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.JunglePlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.OakPlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.SprucePlankPathway;
import us.vombat.buildiblocks.blocks.blocks.pathway.StonePathway;
import us.vombat.buildiblocks.blocks.blocks.pillar.brick.AndesitePillar;
import us.vombat.buildiblocks.blocks.blocks.pillar.brick.DioritePillar;
import us.vombat.buildiblocks.blocks.blocks.pillar.brick.GranitePillar;
import us.vombat.buildiblocks.blocks.blocks.pillar.stone.StonePillar;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedAcaciaLog;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedBirchLog;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedDarkOakLog;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedJungleLog;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedOakLog;
import us.vombat.buildiblocks.blocks.blocks.pillar.wood.CarvedSpruceLog;
import us.vombat.buildiblocks.blocks.blocks.slab.CoarseDirtSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.CobblestoneMossySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.DiamondSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.EmeraldSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.EndBrickSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.GoldSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.HaybaleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.IronSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.LapisSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.ObsidianSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.PrismarineBrickSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.PrismarineDarkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.RedSandstoneSmoothSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.SandstoneSmoothSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.StonebrickCrackedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.StonebrickMossySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.AndesiteBrickSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.AndesitePolishedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.DioriteBrickSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.DioritePolishedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.GraniteBrickSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.brick.GranitePolishedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileBlackSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileBrownSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileCyanSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileGraySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileGreenSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileLightBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileLimeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileMagentaSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileOrangeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytilePinkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytilePurpleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileRedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileSilverSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileWhiteSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.claytile.ClaytileYellowSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassBlackSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassBrownSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassCyanSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassGraySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassGreenSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassLightBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassLimeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassMagentaSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassOrangeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassPinkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassPurpleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassRedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassSilverSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassWhiteSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.glass.GlassYellowSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayBlackSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayBrownSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayCyanSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayGraySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayGreenSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayLightBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayLimeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayMagentaSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayOrangeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayPinkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayPurpleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayRedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclaySilverSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclaySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayWhiteSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.hardclay.HardclayYellowSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakBlackSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakCyanSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakGraySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakGreenSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakLightBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakLimeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakMagentaSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakOrangeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakPinkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakPurpleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakRedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakSilverSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakWhiteSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.paintedplanks.PaintedOakYellowSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolBlackSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolBrownSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolCyanSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolGraySlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolGreenSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolLightBlueSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolLimeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolMagentaSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolOrangeSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolPinkSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolPurpleSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolRedSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolSilverSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolWhiteSlab;
import us.vombat.buildiblocks.blocks.blocks.slab.wool.WoolYellowSlab;
import us.vombat.buildiblocks.blocks.blocks.stair.CobblestoneMossyStair;
import us.vombat.buildiblocks.blocks.blocks.stair.DiamondStair;
import us.vombat.buildiblocks.blocks.blocks.stair.EmeraldStair;
import us.vombat.buildiblocks.blocks.blocks.stair.EndBrickStair;
import us.vombat.buildiblocks.blocks.blocks.stair.GoldStair;
import us.vombat.buildiblocks.blocks.blocks.stair.IronStair;
import us.vombat.buildiblocks.blocks.blocks.stair.LapisStair;
import us.vombat.buildiblocks.blocks.blocks.stair.ObsidianStair;
import us.vombat.buildiblocks.blocks.blocks.stair.PrismarineBrickStair;
import us.vombat.buildiblocks.blocks.blocks.stair.PrismarineDarkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.RedSandstoneSmoothStair;
import us.vombat.buildiblocks.blocks.blocks.stair.SandstoneSmoothStair;
import us.vombat.buildiblocks.blocks.blocks.stair.StoneStair;
import us.vombat.buildiblocks.blocks.blocks.stair.StonebrickCrackedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.StonebrickMossyStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.AndesiteBrickStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.AndesitePolishedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.DioriteBrickStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.DioritePolishedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.GraniteBrickStair;
import us.vombat.buildiblocks.blocks.blocks.stair.brick.GranitePolishedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileBlackStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileBrownStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileCyanStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileGrayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileGreenStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileLightBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileLimeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileMagentaStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileOrangeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytilePinkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytilePurpleStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileRedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileSilverStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileWhiteStair;
import us.vombat.buildiblocks.blocks.blocks.stair.claytile.ClaytileYellowStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassBlackStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassBrownStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassCyanStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassGrayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassGreenStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassLightBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassLimeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassMagentaStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassOrangeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassPinkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassPurpleStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassRedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassSilverStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassWhiteStair;
import us.vombat.buildiblocks.blocks.blocks.stair.glass.GlassYellowStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayBlackStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayBrownStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayCyanStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayGrayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayGreenStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayLightBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayLimeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayMagentaStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayOrangeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayPinkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayPurpleStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayRedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclaySilverStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayWhiteStair;
import us.vombat.buildiblocks.blocks.blocks.stair.hardclay.HardclayYellowStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakBlackStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakCyanStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakGrayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakGreenStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakLightBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakLimeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakMagentaStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakOrangeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakPinkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakPurpleStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakRedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakSilverStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakWhiteStair;
import us.vombat.buildiblocks.blocks.blocks.stair.paintedplanks.PaintedOakYellowStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolBlackStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolBrownStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolCyanStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolGrayStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolGreenStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolLightBlueStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolLimeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolMagentaStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolOrangeStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolPinkStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolPurpleStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolRedStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolSilverStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolWhiteStair;
import us.vombat.buildiblocks.blocks.blocks.stair.wool.WoolYellowStair;
import us.vombat.buildiblocks.blocks.blocks.torch.GoldTorch;
import us.vombat.buildiblocks.blocks.blocks.torch.IronTorch;
import us.vombat.buildiblocks.blocks.blocks.wall.BrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.DiamondWall;
import us.vombat.buildiblocks.blocks.blocks.wall.EmeraldWall;
import us.vombat.buildiblocks.blocks.blocks.wall.EndBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.GoldWall;
import us.vombat.buildiblocks.blocks.blocks.wall.IronWall;
import us.vombat.buildiblocks.blocks.blocks.wall.LapisWall;
import us.vombat.buildiblocks.blocks.blocks.wall.NetherBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.ObsidianWall;
import us.vombat.buildiblocks.blocks.blocks.wall.PrismarineBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.PrismarineDarkWall;
import us.vombat.buildiblocks.blocks.blocks.wall.PurpurBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.QuartzWall;
import us.vombat.buildiblocks.blocks.blocks.wall.RedSandstoneSmoothWall;
import us.vombat.buildiblocks.blocks.blocks.wall.RedSandstoneWall;
import us.vombat.buildiblocks.blocks.blocks.wall.SandstoneSmoothWall;
import us.vombat.buildiblocks.blocks.blocks.wall.SandstoneWall;
import us.vombat.buildiblocks.blocks.blocks.wall.StoneBrickCrackedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.StoneBrickMossyWall;
import us.vombat.buildiblocks.blocks.blocks.wall.StoneBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.StoneWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.AndesiteBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.AndesitePolishedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.DioriteBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.DioritePolishedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.GraniteBrickWall;
import us.vombat.buildiblocks.blocks.blocks.wall.brick.GranitePolishedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayBlackWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayBlueWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayBrownWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayCyanWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayGrayWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayGreenWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayLightBlueWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayLimeWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayMagentaWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayOrangeWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayPinkWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayPurpleWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayRedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclaySilverWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayWhiteWall;
import us.vombat.buildiblocks.blocks.blocks.wall.hardclay.HardclayYellowWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakBlackWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakBlueWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakCyanWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakGrayWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakGreenWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakLightBlueWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakLimeWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakMagentaWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakOrangeWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakPinkWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakPurpleWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakRedWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakSilverWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakWhiteWall;
import us.vombat.buildiblocks.blocks.blocks.wall.paintedplanks.PaintedOakYellowWall;
import us.vombat.buildiblocks.blocks.handlers.BasicBlock;
import us.vombat.buildiblocks.blocks.handlers.FenceBlock;
import us.vombat.buildiblocks.blocks.handlers.PaneBlock;
import us.vombat.buildiblocks.blocks.handlers.PathwayBlock;
import us.vombat.buildiblocks.blocks.handlers.RotatedBlock;
import us.vombat.buildiblocks.blocks.handlers.SlabContainer;
import us.vombat.buildiblocks.blocks.handlers.SlabTranslucentContainer;
import us.vombat.buildiblocks.blocks.handlers.StairBlock;
import us.vombat.buildiblocks.blocks.handlers.StairTranslucentBlock;
import us.vombat.buildiblocks.blocks.handlers.TorchBlock;
import us.vombat.buildiblocks.blocks.handlers.WallBlock;

public class BlockList
{
	public static final List<Block> list = new ArrayList<Block>();

	//Basic Cubed Blocks

	public static final BasicBlock graniteBrick = new GraniteBrick();
	public static final BasicBlock dioriteBrick = new DioriteBrick();
	public static final BasicBlock andesiteBrick = new AndesiteBrick();
	public static final BasicBlock decoratedIron = new EmbellishedIronBlock(Blocks.IRON_BLOCK);
	public static final BasicBlock decoratedGold = new EmbellishedGoldBlock(Blocks.GOLD_BLOCK);
	public static final BasicBlock decoratedDiamond = new EmbellishedDiamondBlock(Blocks.DIAMOND_BLOCK);
	public static final BasicBlock decoratedEmerald = new EmbellishedEmeraldBlock(Blocks.EMERALD_BLOCK);
	public static final BasicBlock carvedOak = new OakCarved();
	public static final BasicBlock carvedSpruce = new SpruceCarved();
	public static final BasicBlock carvedBirch = new BirchCarved();
	public static final BasicBlock carvedJungle = new JungleCarved();
	public static final BasicBlock carvedAcacia = new AcaciaCarved();
	public static final BasicBlock carvedDarkoak = new DarkoakCarved();
	public static final BasicBlock claytileWhite = new ClayTileWhite();
	public static final BasicBlock claytileOrange = new ClayTileOrange();
	public static final BasicBlock claytileMagenta = new ClayTileMagenta();
	public static final BasicBlock claytileLightBlue = new ClayTileLightBlue();
	public static final BasicBlock claytileYellow = new ClayTileYellow();
	public static final BasicBlock claytileLime = new ClayTileLime();
	public static final BasicBlock claytilePink = new ClayTilePink();
	public static final BasicBlock claytileGray = new ClayTileGray();
	public static final BasicBlock claytileSilver = new ClayTileSilver();
	public static final BasicBlock claytileCyan = new ClayTileCyan();
	public static final BasicBlock claytilePurple = new ClayTilePurple();
	public static final BasicBlock claytileBlue = new ClayTileBlue();
	public static final BasicBlock claytileBrown = new ClayTileBrown();
	public static final BasicBlock claytileGreen = new ClayTileGreen();
	public static final BasicBlock claytileRed = new ClayTileRed();
	public static final BasicBlock claytileBlack = new ClayTileBlack();
	public static final BasicBlock claytile = new ClayTile();
/*	public static final BasicBlock paintedOakWhite = new PaintedOakWhite();
	public static final BasicBlock paintedOakOrange = new PaintedOakOrange();
	public static final BasicBlock paintedOakMagenta = new PaintedOakMagenta();
	public static final BasicBlock paintedOakLightBlue = new PaintedOakLightBlue();
	public static final BasicBlock paintedOakYellow = new PaintedOakYellow();
	public static final BasicBlock paintedOakLime = new PaintedOakLime();
	public static final BasicBlock paintedOakPink = new PaintedOakPink();
	public static final BasicBlock paintedOakGray = new PaintedOakGray();
	public static final BasicBlock paintedOakSilver = new PaintedOakSilver();
	public static final BasicBlock paintedOakCyan = new PaintedOakCyan();
	public static final BasicBlock paintedOakPurple = new PaintedOakPurple();
	public static final BasicBlock paintedOakBlue = new PaintedOakBlue();
	public static final BasicBlock paintedOakGreen = new PaintedOakGreen();
	public static final BasicBlock paintedOakRed = new PaintedOakRed();
	public static final BasicBlock paintedOakBlack = new PaintedOakBlack();*/


	//Misc Blocks

	public static final PaneBlock paperWall = new PaperWall();


	//Lattice Blocks

	public static final PaneBlock acaciaLattice = new AcaciaLattice();
	public static final PaneBlock birchLattice = new BirchLattice();
	public static final PaneBlock darkoakLattice = new DarkOakLattice();
	public static final PaneBlock jungleLattice = new JungleLattice();
	public static final PaneBlock oakLattice = new OakLattice();
	public static final PaneBlock spruceLattice = new SpruceLattice();


	//Fence Blocks

	public static final FenceBlock ironFence = new IronFence(Blocks.IRON_BLOCK);
	public static final FenceBlock goldFence = new GoldFence(Blocks.GOLD_BLOCK);
	public static final FenceBlock diamondFence = new DiamondFence(Blocks.DIAMOND_BLOCK);
	public static final FenceBlock emeraldFence = new EmeraldFence(Blocks.EMERALD_BLOCK);


	//Decor Pathway Blocks

	public static final PathwayBlock stonePathway = new StonePathway(Blocks.STONE);
	public static final PathwayBlock oakPathway = new OakPlankPathway(Blocks.PLANKS);
	public static final PathwayBlock sprucePathway = new SprucePlankPathway(Blocks.PLANKS);
	public static final PathwayBlock birchPathway = new BirchPlankPathway(Blocks.PLANKS);
	public static final PathwayBlock junglePathway = new JunglePlankPathway(Blocks.PLANKS);
	public static final PathwayBlock acaciaPathway = new AcaciaPlankPathway(Blocks.PLANKS);
	public static final PathwayBlock darkOakPathway = new DarkOakPlankPathway(Blocks.PLANKS);


	//Pillar Blocks

	public static final TorchBlock ironTorch = new IronTorch();
	public static final TorchBlock goldTorch = new GoldTorch();
	public static final RotatedBlock stonePillar = new StonePillar(Blocks.STONE);
	public static final RotatedBlock andesitePillar = new AndesitePillar(Blocks.STONE);
	public static final RotatedBlock dioritePillar = new DioritePillar(Blocks.STONE);
	public static final RotatedBlock granitePillar = new GranitePillar(Blocks.STONE);
	public static final RotatedBlock oakPillar = new CarvedOakLog(Blocks.LOG);
	public static final RotatedBlock sprucePillar = new CarvedSpruceLog(Blocks.LOG);
	public static final RotatedBlock birchPillar = new CarvedBirchLog(Blocks.LOG);
	public static final RotatedBlock junglePillar = new CarvedJungleLog(Blocks.LOG);
	public static final RotatedBlock acaciaPillar = new CarvedAcaciaLog(Blocks.LOG2);
	public static final RotatedBlock darkOakPillar = new CarvedDarkOakLog(Blocks.LOG2);


	//Stair Blocks

	public static final StairBlock stoneStair = new StoneStair(Blocks.STONE);
	public static final StairBlock stonebrickCrackStair = new StonebrickCrackedStair(Blocks.STONEBRICK);
	public static final StairBlock stonebrickMossStair = new StonebrickMossyStair(Blocks.STONEBRICK);
	public static final StairBlock graniteBrickStair = new GraniteBrickStair(Blocks.STONEBRICK);
	public static final StairBlock granitePolishStair = new GranitePolishedStair(Blocks.STONE);
	public static final StairBlock dioriteBrickStair = new DioriteBrickStair(Blocks.STONEBRICK);
	public static final StairBlock dioritePolishStair = new DioritePolishedStair(Blocks.STONE);
	public static final StairBlock andesiteBrickStair = new AndesiteBrickStair(Blocks.STONEBRICK);
	public static final StairBlock andesitePolishStair = new AndesitePolishedStair(Blocks.STONE);
	public static final StairBlock cobbleMossyStair = new CobblestoneMossyStair(Blocks.COBBLESTONE);
	public static final StairBlock ironStair = new IronStair(Blocks.IRON_BLOCK);
	public static final StairBlock goldStair = new GoldStair(Blocks.GOLD_BLOCK);
	public static final StairBlock diamondStair = new DiamondStair(Blocks.DIAMOND_BLOCK);
	public static final StairBlock emeraldStair = new EmeraldStair(Blocks.EMERALD_BLOCK);
	public static final StairBlock lapisStair = new LapisStair(Blocks.LAPIS_BLOCK);
	public static final StairBlock obsidianStair = new ObsidianStair(Blocks.OBSIDIAN);
	public static final StairBlock endBrickStair = new EndBrickStair(Blocks.END_BRICKS);
	public static final StairBlock prismarineBrickStair = new PrismarineBrickStair(Blocks.PRISMARINE);
	public static final StairBlock prismarineDarkStair = new PrismarineDarkStair(Blocks.PRISMARINE);
	public static final StairBlock sandstoneSmoothStair = new SandstoneSmoothStair(Blocks.SANDSTONE);
	public static final StairBlock redSmoothSandstoneStair = new RedSandstoneSmoothStair(Blocks.RED_SANDSTONE);

/*	public static final StairBlock paintedOakWhiteStair = new PaintedOakWhiteStair(Blocks.PLANKS);
	public static final StairBlock paintedOakOrangeStair = new PaintedOakOrangeStair(Blocks.PLANKS);
	public static final StairBlock paintedOakMagentaStair = new PaintedOakMagentaStair(Blocks.PLANKS);
	public static final StairBlock paintedOakLightBlueStair = new PaintedOakLightBlueStair(Blocks.PLANKS);
	public static final StairBlock paintedOakYellowStair = new PaintedOakYellowStair(Blocks.PLANKS);
	public static final StairBlock paintedOakLimeStair = new PaintedOakLimeStair(Blocks.PLANKS);
	public static final StairBlock paintedOakPinkStair = new PaintedOakPinkStair(Blocks.PLANKS);
	public static final StairBlock paintedOakGrayStair = new PaintedOakGrayStair(Blocks.PLANKS);
	public static final StairBlock paintedOakSilverStair = new PaintedOakSilverStair(Blocks.PLANKS);
	public static final StairBlock paintedOakCyanStair = new PaintedOakCyanStair(Blocks.PLANKS);
	public static final StairBlock paintedOakPurpleStair = new PaintedOakPurpleStair(Blocks.PLANKS);
	public static final StairBlock paintedOakBlueStair = new PaintedOakBlueStair(Blocks.PLANKS);
	public static final StairBlock paintedOakGreenStair = new PaintedOakGreenStair(Blocks.PLANKS);
	public static final StairBlock paintedOakRedStair = new PaintedOakRedStair(Blocks.PLANKS);
	public static final StairBlock paintedOakBlackStair = new PaintedOakBlackStair(Blocks.PLANKS);*/

	public static final StairBlock claytileStair = new ClaytileStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileWhiteStair = new ClaytileWhiteStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileOrangeStair = new ClaytileOrangeStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileMagentaStair = new ClaytileMagentaStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileLightBlueStair = new ClaytileLightBlueStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileYellowStair = new ClaytileYellowStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileLimeStair = new ClaytileLimeStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytilePinkStair = new ClaytilePinkStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileGrayStair = new ClaytileGrayStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileSilverStair = new ClaytileSilverStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileCyanStair = new ClaytileCyanStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytilePurpleStair = new ClaytilePurpleStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileBlueStair = new ClaytileBlueStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileBrownStair = new ClaytileBrownStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileGreenStair = new ClaytileGreenStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileRedStair = new ClaytileRedStair(Blocks.HARDENED_CLAY);
	public static final StairBlock claytileBlackStair = new ClaytileBlackStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayStair = new HardclayStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayWhiteStair = new HardclayWhiteStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayOrangeStair = new HardclayOrangeStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayMagentaStair = new HardclayMagentaStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayLightBlueStair = new HardclayLightBlueStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayYellowStair = new HardclayYellowStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayLimeStair = new HardclayLimeStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayPinkStair = new HardclayPinkStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayGrayStair = new HardclayGrayStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclaySilverStair = new HardclaySilverStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayCyanStair = new HardclayCyanStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayPurpleStair = new HardclayPurpleStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayBlueStair = new HardclayBlueStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayBrownStair = new HardclayBrownStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayGreenStair = new HardclayGreenStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayRedStair = new HardclayRedStair(Blocks.HARDENED_CLAY);
	public static final StairBlock hardclayBlackStair = new HardclayBlackStair(Blocks.HARDENED_CLAY);
	public static final StairBlock woolWhiteStair = new WoolWhiteStair(Blocks.WOOL);
	public static final StairBlock woolOrangeStair = new WoolOrangeStair(Blocks.WOOL);
	public static final StairBlock woolMagentaStair = new WoolMagentaStair(Blocks.WOOL);
	public static final StairBlock woolLightBlueStair = new WoolLightBlueStair(Blocks.WOOL);
	public static final StairBlock woolYellowStair = new WoolYellowStair(Blocks.WOOL);
	public static final StairBlock woolLimeStair = new WoolLimeStair(Blocks.WOOL);
	public static final StairBlock woolPinkStair = new WoolPinkStair(Blocks.WOOL);
	public static final StairBlock woolGrayStair = new WoolGrayStair(Blocks.WOOL);
	public static final StairBlock woolSilverStair = new WoolSilverStair(Blocks.WOOL);
	public static final StairBlock woolCyanStair = new WoolCyanStair(Blocks.WOOL);
	public static final StairBlock woolPurpleStair = new WoolPurpleStair(Blocks.WOOL);
	public static final StairBlock woolBlueStair = new WoolBlueStair(Blocks.WOOL);
	public static final StairBlock woolBrownStair = new WoolBrownStair(Blocks.WOOL);
	public static final StairBlock woolGreenStair = new WoolGreenStair(Blocks.WOOL);
	public static final StairBlock woolRedStair = new WoolRedStair(Blocks.WOOL);
	public static final StairBlock woolBlackStair = new WoolBlackStair(Blocks.WOOL);
	public static final StairTranslucentBlock glassStair = new GlassStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassWhiteStair = new GlassWhiteStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassOrangeStair = new GlassOrangeStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassMagentaStair = new GlassMagentaStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassLightBlueStair = new GlassLightBlueStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassYellowStair = new GlassYellowStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassLimeStair = new GlassLimeStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassPinkStair = new GlassPinkStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassGrayStair = new GlassGrayStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassSilverStair = new GlassSilverStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassCyanStair = new GlassCyanStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassPurpleStair = new GlassPurpleStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassBlueStair = new GlassBlueStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassBrownStair = new GlassBrownStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassGreenStair = new GlassGreenStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassRedStair = new GlassRedStair(Blocks.GLASS);
	public static final StairTranslucentBlock glassBlackStair = new GlassBlackStair(Blocks.GLASS);


	//Slab Blocks

	public static final SlabContainer stonebrickCrackSlab = new StonebrickCrackedSlab(Blocks.STONEBRICK);
	public static final SlabContainer stonebrickMossSlab = new StonebrickMossySlab(Blocks.STONEBRICK);
	public static final SlabContainer andesitePolishSlab = new AndesitePolishedSlab(Blocks.STONE);
	public static final SlabContainer andesiteBrickSlab = new AndesiteBrickSlab(Blocks.STONE);
	public static final SlabContainer dioritePolishSlab = new DioritePolishedSlab(Blocks.STONE);
	public static final SlabContainer dioriteBrickSlab = new DioriteBrickSlab(Blocks.STONE);
	public static final SlabContainer granitePolishSlab = new GranitePolishedSlab(Blocks.STONE);
	public static final SlabContainer graniteBrickSlab = new GraniteBrickSlab(Blocks.STONE);
	public static final SlabContainer cobbleMossySlab = new CobblestoneMossySlab(Blocks.MOSSY_COBBLESTONE);
	public static final SlabContainer obsidianSlab = new ObsidianSlab(Blocks.OBSIDIAN);
	public static final SlabContainer endBrickSlab = new EndBrickSlab(Blocks.END_BRICKS);
	public static final SlabContainer prismarineDarkSlab = new PrismarineDarkSlab(Blocks.PRISMARINE);
	public static final SlabContainer prismarineBrickSlab = new PrismarineBrickSlab(Blocks.PRISMARINE);
	public static final SlabContainer sandstoneSmoothSlab = new SandstoneSmoothSlab(Blocks.SANDSTONE);
	public static final SlabContainer redSmoothSandstoneSlab = new RedSandstoneSmoothSlab(Blocks.RED_SANDSTONE);
	public static final SlabContainer coarseDirtSlab = new CoarseDirtSlab(Blocks.DIRT);
	public static final SlabContainer ironSlab = new IronSlab(Blocks.IRON_BLOCK);
	public static final SlabContainer goldSlab = new GoldSlab(Blocks.GOLD_BLOCK);
	public static final SlabContainer diamondSlab = new DiamondSlab(Blocks.DIAMOND_BLOCK);
	public static final SlabContainer emeraldSlab = new EmeraldSlab(Blocks.EMERALD_BLOCK);
	public static final SlabContainer lapisSlab = new LapisSlab(Blocks.LAPIS_BLOCK);
	public static final SlabContainer haybaleSlab = new HaybaleSlab(Blocks.HAY_BLOCK);

/*	public static final SlabContainer paintedOakWhiteSlab = new PaintedOakWhiteSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakOrangeSlab = new PaintedOakOrangeSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakMagentaSlab = new PaintedOakMagentaSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakLightBlueSlab = new PaintedOakLightBlueSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakYellowSlab = new PaintedOakYellowSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakLimeSlab = new PaintedOakLimeSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakPinkSlab = new PaintedOakPinkSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakGraySlab = new PaintedOakGraySlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakSilverSlab = new PaintedOakSilverSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakCyanSlab = new PaintedOakCyanSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakPurpleSlab = new PaintedOakPurpleSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakBlueSlab = new PaintedOakBlueSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakGreenSlab = new PaintedOakGreenSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakRedSlab = new PaintedOakRedSlab(Blocks.PLANKS);
	public static final SlabContainer paintedOakBlackSlab = new PaintedOakBlackSlab(Blocks.PLANKS);*/

	public static final SlabContainer claytileSlab = new ClaytileSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileWhiteSlab = new ClaytileWhiteSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileOrangeSlab = new ClaytileOrangeSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileMagentaSlab = new ClaytileMagentaSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileLightBlueSlab = new ClaytileLightBlueSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileYellowSlab = new ClaytileYellowSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileLimeSlab = new ClaytileLimeSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytilePinkSlab = new ClaytilePinkSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileGraySlab = new ClaytileGraySlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileSilverSlab = new ClaytileSilverSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileCyanSlab = new ClaytileCyanSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytilePurpleSlab = new ClaytilePurpleSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileBlueSlab = new ClaytileBlueSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileBrownSlab = new ClaytileBrownSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileGreenSlab = new ClaytileGreenSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileRedSlab = new ClaytileRedSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer claytileBlackSlab = new ClaytileBlackSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclaySlab = new HardclaySlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayWhiteSlab = new HardclayWhiteSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayOrangeSlab = new HardclayOrangeSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayMagentaSlab = new HardclayMagentaSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayLightBlueSlab = new HardclayLightBlueSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayYellowSlab = new HardclayYellowSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayLimeSlab = new HardclayLimeSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayPinkSlab = new HardclayPinkSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayGraySlab = new HardclayGraySlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclaySilverSlab = new HardclaySilverSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayCyanSlab = new HardclayCyanSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayPurpleSlab = new HardclayPurpleSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayBlueSlab = new HardclayBlueSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayBrownSlab = new HardclayBrownSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayGreenSlab = new HardclayGreenSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayRedSlab = new HardclayRedSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer hardclayBlackSlab = new HardclayBlackSlab(Blocks.HARDENED_CLAY);
	public static final SlabContainer woolWhiteSlab = new WoolWhiteSlab(Blocks.WOOL);
	public static final SlabContainer woolOrangeSlab = new WoolOrangeSlab(Blocks.WOOL);
	public static final SlabContainer woolMagentaSlab = new WoolMagentaSlab(Blocks.WOOL);
	public static final SlabContainer woolLightBlueSlab = new WoolLightBlueSlab(Blocks.WOOL);
	public static final SlabContainer woolYellowSlab = new WoolYellowSlab(Blocks.WOOL);
	public static final SlabContainer woolLimeSlab = new WoolLimeSlab(Blocks.WOOL);
	public static final SlabContainer woolPinkSlab = new WoolPinkSlab(Blocks.WOOL);
	public static final SlabContainer woolGraySlab = new WoolGraySlab(Blocks.WOOL);
	public static final SlabContainer woolSilverSlab = new WoolSilverSlab(Blocks.WOOL);
	public static final SlabContainer woolCyanSlab = new WoolCyanSlab(Blocks.WOOL);
	public static final SlabContainer woolPurpleSlab = new WoolPurpleSlab(Blocks.WOOL);
	public static final SlabContainer woolBlueSlab = new WoolBlueSlab(Blocks.WOOL);
	public static final SlabContainer woolBrownSlab = new WoolBrownSlab(Blocks.WOOL);
	public static final SlabContainer woolGreenSlab = new WoolGreenSlab(Blocks.WOOL);
	public static final SlabContainer woolRedSlab = new WoolRedSlab(Blocks.WOOL);
	public static final SlabContainer woolBlackSlab = new WoolBlackSlab(Blocks.WOOL);
	public static final SlabTranslucentContainer glassSlab = new GlassSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassWhiteSlab = new GlassWhiteSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassOrangeSlab = new GlassOrangeSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassMagentaSlab = new GlassMagentaSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassLightBlueSlab = new GlassLightBlueSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassYellowSlab = new GlassYellowSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassLimeSlab = new GlassLimeSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassPinkSlab = new GlassPinkSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassGraySlab = new GlassGraySlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassSilverSlab = new GlassSilverSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassCyanSlab = new GlassCyanSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassPurpleSlab = new GlassPurpleSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassBlueSlab = new GlassBlueSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassBrownSlab = new GlassBrownSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassGreenSlab = new GlassGreenSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassRedSlab = new GlassRedSlab(Blocks.GLASS);
	public static final SlabTranslucentContainer glassBlackSlab = new GlassBlackSlab(Blocks.GLASS);


	//Wall Blocks

	public static final WallBlock stoneWall = new StoneWall(Blocks.STONE);
	public static final WallBlock granitePolishWall = new GranitePolishedWall(Blocks.STONE);
	public static final WallBlock graniteBrickWall = new GraniteBrickWall(Blocks.STONE);
	public static final WallBlock dioritePolishWall = new DioritePolishedWall(Blocks.STONE);
	public static final WallBlock dioriteBrickWall = new DioriteBrickWall(Blocks.STONE);
	public static final WallBlock andesitePolishWall = new AndesitePolishedWall(Blocks.STONE);
	public static final WallBlock andesiteBrickWall = new AndesiteBrickWall(Blocks.STONE);
	public static final WallBlock brickWall = new BrickWall(Blocks.BRICK_BLOCK);
	public static final WallBlock ironWall = new IronWall(Blocks.IRON_BLOCK);
	public static final WallBlock diamondWall = new DiamondWall(Blocks.DIAMOND_BLOCK);
	public static final WallBlock goldWall = new GoldWall(Blocks.GOLD_BLOCK);
	public static final WallBlock emeraldWall = new EmeraldWall(Blocks.EMERALD_BLOCK);
	public static final WallBlock lapisWall = new LapisWall(Blocks.LAPIS_BLOCK);
	public static final WallBlock obsidianWall = new ObsidianWall(Blocks.OBSIDIAN);
	public static final WallBlock netherBrickWall = new NetherBrickWall(Blocks.NETHER_BRICK);
	public static final WallBlock endBrickWall = new EndBrickWall(Blocks.END_BRICKS);
	public static final WallBlock purpurBrickWall = new PurpurBrickWall(Blocks.PURPUR_BLOCK);
	public static final WallBlock quartzWall = new QuartzWall(Blocks.QUARTZ_BLOCK);
	public static final WallBlock prismarineBrickWall = new PrismarineBrickWall(Blocks.PRISMARINE);
	public static final WallBlock prismarineDarkWall = new PrismarineDarkWall(Blocks.PRISMARINE);
	public static final WallBlock stonebrickCrackWall = new StoneBrickCrackedWall(Blocks.STONEBRICK);
	public static final WallBlock stonebrickMossWall = new StoneBrickMossyWall(Blocks.STONEBRICK);
	public static final WallBlock stonebrickWall = new StoneBrickWall(Blocks.STONEBRICK);
	public static final WallBlock sandstoneSmoothWall = new SandstoneSmoothWall(Blocks.SANDSTONE);
	public static final WallBlock sandstoneWall = new SandstoneWall(Blocks.SANDSTONE);
	public static final WallBlock redSmoothSandstoneWall = new RedSandstoneSmoothWall(Blocks.RED_SANDSTONE);
	public static final WallBlock redsandstoneWall = new RedSandstoneWall(Blocks.RED_SANDSTONE);

/*	public static final WallBlock paintedOakWhiteWall = new PaintedOakWhiteWall(Blocks.PLANKS);
	public static final WallBlock paintedOakOrangeWall = new PaintedOakOrangeWall(Blocks.PLANKS);
	public static final WallBlock paintedOakMagentaWall = new PaintedOakMagentaWall(Blocks.PLANKS);
	public static final WallBlock paintedOakLightBlueWall = new PaintedOakLightBlueWall(Blocks.PLANKS);
	public static final WallBlock paintedOakYellowWall = new PaintedOakYellowWall(Blocks.PLANKS);
	public static final WallBlock paintedOakLimeWall = new PaintedOakLimeWall(Blocks.PLANKS);
	public static final WallBlock paintedOakPinkWall = new PaintedOakPinkWall(Blocks.PLANKS);
	public static final WallBlock paintedOakGrayWall = new PaintedOakGrayWall(Blocks.PLANKS);
	public static final WallBlock paintedOakSilverWall = new PaintedOakSilverWall(Blocks.PLANKS);
	public static final WallBlock paintedOakCyanWall = new PaintedOakCyanWall(Blocks.PLANKS);
	public static final WallBlock paintedOakPurpleWall = new PaintedOakPurpleWall(Blocks.PLANKS);
	public static final WallBlock paintedOakBlueWall = new PaintedOakBlueWall(Blocks.PLANKS);
	public static final WallBlock paintedOakGreenWall = new PaintedOakGreenWall(Blocks.PLANKS);
	public static final WallBlock paintedOakRedWall = new PaintedOakRedWall(Blocks.PLANKS);
	public static final WallBlock paintedOakBlackWall = new PaintedOakBlackWall(Blocks.PLANKS);*/

	public static final WallBlock hardclayWall = new HardclayWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayWhiteWall = new HardclayWhiteWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayOrangeWall = new HardclayOrangeWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayMagentaWall = new HardclayMagentaWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayLightBlueWall = new HardclayLightBlueWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayYellowWall = new HardclayYellowWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayLimeWall = new HardclayLimeWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayPinkWall = new HardclayPinkWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayGrayWall = new HardclayGrayWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclaySilverWall = new HardclaySilverWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayCyanWall = new HardclayCyanWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayPurpleWall = new HardclayPurpleWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayBlueWall = new HardclayBlueWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayBrownWall = new HardclayBrownWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayGreenWall = new HardclayGreenWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayRedWall = new HardclayRedWall(Blocks.HARDENED_CLAY);
	public static final WallBlock hardclayBlackWall = new HardclayBlackWall(Blocks.HARDENED_CLAY);
/*	public static final WallTranslucentBlock glassWall = new GlassWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassWhiteWall = new GlassWhiteWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassOrangeWall = new GlassOrangeWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassMagentaWall = new GlassMagentaWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassLightBlueWall = new GlassLightBlueWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassYellowWall = new GlassYellowWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassLimeWall = new GlassLimeWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassPinkWall = new GlassPinkWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassGrayWall = new GlassGrayWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassSilverWall = new GlassSilverWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassCyanWall = new GlassCyanWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassPurpleWall = new GlassPurpleWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassBlueWall = new GlassBlueWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassBrownWall = new GlassBrownWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassGreenWall = new GlassGreenWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassRedWall = new GlassRedWall(Blocks.GLASS);
	public static final WallTranslucentBlock glassBlackWall = new GlassBlackWall(Blocks.GLASS);*/
}